#!/usr/bin/env python3
"""Import HYG 4.2 (CC BY-SA 4.0); input is the original publisher .csv.gz.
Usage: python3 tools/import-star-catalog.py /path/to/hygdata_v42.csv.gz
Download: https://www.astronexus.com/downloads/catalogs/hygdata_v42.csv.gz
No network requests; verify the pinned source before changing generated data.
"""
import base64, csv, gzip, hashlib, math, struct, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SOURCE_SHA256 = '5ca9431ff364c8002a4a3efa91b2b9296746aea1543374db4cb6b4fab049d601'
source = Path(sys.argv[1])
assert hashlib.sha256(source.read_bytes()).hexdigest() == SOURCE_SHA256, 'Unexpected source version'
with gzip.open(source, 'rt', newline='') as f:
    rows = [r for r in csv.DictReader(f) if r['id'] != '0' and r['mag'] and float(r['mag']) <= 6.5]
rows.sort(key=lambda r: (float(r['ra']), float(r['dec']), int(r['id'])))
def quantize(x, limit):
    return max(0, min(limit, math.floor(x + 0.5)))
data = bytearray()
for r in rows:
    ra, dec, mag = float(r['ra']) * 15, float(r['dec']), float(r['mag'])
    bv = float(r['ci']) if r['ci'] else 0.65  # Neutral colour for missing B-V (40 records).
    assert 0 <= ra < 360 and -90 <= dec <= 90 and math.isfinite(mag) and math.isfinite(bv)
    data += struct.pack('<HHBB', quantize(ra / 360 * 65535, 65535), quantize((dec + 90) / 180 * 65535, 65535),
                        quantize((mag + 2) * 25.5, 255), quantize((bv + 0.5) * 85, 255))
output = f'''  // Generated by tools/import-star-catalog.py. Do not hand-edit.
  // HYG 4.2 — David Nash / Astronomy Nexus. SPDX-License-Identifier: CC-BY-SA-4.0
  // https://www.astronexus.com/projects/hyg — see licenses/HYG-NOTICE.md and THIRD_PARTY_NOTICES.md.
  // Adaptation: Sun excluded; V <= 6.5 selected; J2000 RA/Dec, V and B-V quantized to 6 bytes/star.
  // Missing B-V uses 0.65; no distances, proper motion or HYG names are included.
  // Original gzip SHA-256: {SOURCE_SHA256}
  const STAR_CATALOG_COUNT = {len(rows)};
  const STAR_B64 = /*STARS*/"{base64.b64encode(data).decode()}";
'''
(ROOT / 'src/data/star-catalog.js').write_text(output)
print(f'HYG 4.2: {len(rows)} stars, {len(data)} packed bytes')
